### ISSUE TITLE
Getting erros when trying to use this.

### ISSUE THREAD

**Issue by thepenguinthatwants** [intrntbrn/icon_customizer#1]
This looks like a awesome project, being wanting to find a way to add icon for ST, as I am using only icons and no text. Having St etc its just leaving an empty blank.

When trying to apply icon_customizer  I get errors such as 

78. in local 'func'
438 in function awful.screen.connect_for_each_screen
main chunk
attempt to call nil value (field 'at_screen_connect')

And the corresponding lines contains these.

I am not sure how to fix or why it causes problems.

```
-- Create a wibox for each screen and add it
awful.screen.connect_for_each_screen(function(s) beautiful.at_screen_connect(s) end)
```

```
if beautiful.wallpaper then
    for s = 1, screen.count() do
        if s < 2 then
          gears.wallpaper.maximized("/wallie.jpg", s, true)
        else
          gears.wallpaper.maximized("/loner.jpg", s, true)
        end
    end
  end
```

I've added these to my rc.lua
```
require('icon_customizer'){ delay = 0.2 }

theme.ic_icons = {
	["st"] = "utils/vim.png"
}
```

**Comment by intrntbrn** [comment]
Please define your custom icons in `theme.lua`, not `rc.lua`. 

`rc.lua`: 

```
require('icon_customizer'){ delay = 0.2 }
```

`theme.lua`:

```
theme.ic_icons = {
	["st"] = "utils/vim.png" -- also use absolute path. check readme!
}
```

**Comment by thepenguinthatwants** [comment]
Hi,
Thanks I've gotten it to work. AND ITS FRICKIN AWESOME!
