### ISSUE TITLE
Dynamic icons not working without changing the window name

### ISSUE THREAD

**Issue by MartinRamm** [intrntbrn/icon_customizer#2]
First of all, I would like to thank you for your awesome work here, I enjoy the results of using it every day.

However, I have found a small bug with dynamic icons. If a new window spawns whose class is included in the `dynamic_classes` list, and it already spawns with a name that matches a key in the `dynamic_icons` table, the window's icon is not changed.

Example (using the `kitty` terminal emulator):
```lua
require('icon_customizer')({
  dynamic_classes = {"kitty"},
  dynamic_icons = {
    ["^test$"] = "/path/to/icon",
  }
})
```

With the above in your `rc.lua` file, launch the command `kitty --title 'asdf' nano /tmp/test`. You will notice that the icon does not change, because the terminal window already has the name `test` when it spawns. If you keep the window open and restart awesome, the icon changes correctly.

If you launch the command `kitty zsh -i -c 'title "asdf"; nano /tmp/test'` (`-i` stands for interactive and is required for zsh to actually change the window name when executing the `title` command), the window launches with the name `kitty`. Then when zsh runs the `title` command, the window name changes to "asdf" and the icon is correctly displayed.

I would be willing to provide a PR to fix this issue, but didn't want to do so without asking you first.

**Comment by intrntbrn** [comment]
Thank you for reporting the issue!

**Comment by MartinRamm** [comment]
That was quick, thank you for the fix :)

One more thing: could you provide a license for your project?
